# Generated by Django 2.1 on 2019-12-24 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 12, 23, 59, 999000)),
        ),
        migrations.AlterField(
            model_name='phone',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 12, 23, 59, 999000)),
        ),
        migrations.AlterModelTable(
            name='phone',
            table='phones',
        ),
    ]
